# Generated by Django 4.2.6 on 2024-01-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0002_remove_tweet_nickname_tweet_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etkinlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('baslangic_saati', models.DateTimeField()),
                ('bitis_saati', models.DateTimeField()),
            ],
        ),
    ]
