# Generated by Django 4.2.6 on 2024-01-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0003_etkinlik'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlik',
            name='price',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='vat_price',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
