# Generated by Django 4.2.6 on 2024-01-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0004_etkinlik_price_etkinlik_vat_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlik',
            name='total_price_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
