# Generated by Django 4.2.6 on 2024-05-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0006_etkinlik_total_price_vat_currency_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Etkinlik',
        ),
    ]
