# Generated by Django 4.2.6 on 2024-05-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0009_alter_reklam_goruntuleme_sayisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reklam',
            name='tiklama_sayisi',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tıklama Sayısı'),
        ),
    ]
