# Generated by Django 4.2.6 on 2024-05-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0010_alter_reklam_tiklama_sayisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reklam',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Etkileşim'),
        ),
    ]
