# Generated by Django 4.2.6 on 2024-05-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useridentity',
            name='expires_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useridentity',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
